#!/bin/bash

#*********************************************************************#
#       AUTHOR: SRIHARSHA VOGETI				      #
#	EMAIL: vogetisri.harsha@research.iiit.ac.in                   #
#   	SOURCE:                                                       #
#   	DESCRIPTION: pCNVD PIPELINE SCRIPT                            #
#   	LAST UPDATED: 18/06/16                                        #
#*********************************************************************#

shopt -s extglob
#set -e 
start_time=`date +%s`


#PARAMETERS WITH DEFAULT VALUES
no_of_procs=32;		# number of processes
input_file="";		# INPUT FILE NAME && MANDATORY PARAMETER
mappability_file=""; 	# MAPPABILITY FILE NAME && MANDATORY PARAMETER
window_file=""; 	# BED FILE CONTAINING WINDOWS && required
output="";      	# OUTPUT PREFIX && MANDATORY PARAMETER
mapThres=0.5;		# mappability threshold

# Flags used
MEDIANGCFLAG=0;		# flag for yoon et al method (GC-correction)
MEDIANMAPFLAG=0;		# flag for yoon et al method (Mappability correction)
LOESSGCFLAG=0;		# flag for loess GC correction method
gcFlag=0;


# constants to be used 
SOURCEDIR=$(dirname $(readlink -f $0)); # SOURCE DIRECTORY 
randomString=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)


# function to correct gc-bias corrected read depths using Yoon et al method 
# uses external R script 
function runMedianGCcorrection() {
	awk '{print $3}' $1 | paste - $2 > ${output}_GC_correction_input.txt
	Rscript --slave ${SOURCEDIR}/source/R/gcCorrectionYoon.R ${output}_GC_correction_input.txt "gc" > ${output}_GC_correction_output.txt;
	paste $1 ${output}_GC_correction_output.txt | awk '{print $1,$2,$5,$4}' > temp_${randomString}.txt
    mv temp_${randomString}.txt $1
    rm ${output}_GC_correction_input.txt ${output}_GC_correction_output.txt temp_${randomString}.txt;
}

# function calls an external script loessGCCorrection.R
# does gc correction using loess method
function runLoessGCcorrection() {
	awk '{print $3}' $1 > ${output}_GC_correction.txt
	Rscript --slave ${SOURCEDIR}/source/R/loessGCCorrection.R ${output}_GC_correction.txt $2
	paste $1 ${output}_GC_correction.txt | awk '{print $1,$2,$5,$4}' > temp_${randomString}.txt
	mv temp_${randomString}.txt $1
	rm ${output}_GC_correction.txt temp_${randomString}.txt;
}


# Function to correct mappability using Yoon et al method
# Similar to above function
# Instead of GC score , mappability score is passed. 
function runMedianMapCorrection(){
	awk '{print $3,$4}' $1  > ${output}_map_correction_input.txt
	Rscript --slave ${SOURCEDIR}/source/R/gcCorrectionYoon.R ${output}_map_correction_input.txt "map"> ${output}_map_correction_output.txt
	paste $1 ${output}_map_correction_output.txt | awk '{print $1,$2,$5,$4}' > temp_${randomString}.txt
	mv temp_${randomString}.txt $1
	rm ${output}_map_correction_input.txt ${output}_map_correction_output.txt temp_${randomString}.txt
}

#***************************************#
#	READ OPTIONS FROM CMD 		#
#	AND SET PARAMETERS		#
#***************************************#

SHORTOPTS="ybp:i:o:m:z:"
LONGOPTS="gcfile:,mapThres:,help,medianGC,medianMap,loessGC"
PROGNAME="preprocess.sh"
ARGS=$(getopt -s bash --options $SHORTOPTS  --longoptions $LONGOPTS --name $PROGNAME -- "$@" ) 

eval set -- "$ARGS"
while true; do
	case "$1" in 
	-p) no_of_procs="$2"; shift 2 ;;
	-i) input_file="$2"; shift 2;;
	-o) output="$2"; shift 2;;
	-m) mappability_file="$2"; shift 2;;
	-z) window_file="$2"; shift 2;;
	-y) MEDIANGCFLAG=1; MEDIANMAPFLAG=1; shift ;;
	--gcfile) gcFile="$2"; gcFlag=1; shift 2; ;;
	--help) echo "Usage: preprocess -i <input BAM> -o <output Prefix> -m <mappability file> -z <bin file>";
		exit 1; ;;
	--mapThres) mapThres="$2" ; shift 2; ;;
	--medianGC) MEDIANGCFLAG=1; shift ;; 
	--medianMap) MEDIANMAPFLAG=1; shift ;;
	--loessGC) LOESSGCFLAG=1; shift ;;
	--) shift; break;;
	*) echo "Error: Something wrong with the parameters"; 
	echo "Requred parameters: -i -o -m -z "; exit 1;;
	esac 
done



# MINIMUM REQUIRED PARAMETERS
if [[ -z "$input_file" || -z "$window_file" || -z "$mappability_file" || -z "$output" ]]; then
	echo "Missing one of the required parameters: window_file (-z) mappability_file (-m) input_file (-i) output (-o) " >&2
	exit 
fi

# FILE DOESNT EXIST ERROR
if [[ ! -f $window_file || ! -f $input_file || ! -f $mappability_file ]]; then 
	echo "One of the input files not found" >&2
	exit 1
fi
if [[ $MEDIANGCFLAG -eq 1 ]]; then 
	if [[ $gcFlag -eq 1 ]];then
		gcFlag=1;
	else
		echo "ERROR: -y flag requires --gcfile argument" >&2 ;
		exit 1
	fi
fi	

#***********************************************#
#	MAIN FUNCTION STARTS HERE		#
#	PRECPROCESS-SEGMENTATION-POSTPROCESS	#
#***********************************************#

# DATA PREPARATION AND FILTERING 
Rscript --slave ${SOURCEDIR}/R/CalculateCoverage.R ${input_file} ${output} ${window_size} ${chromosome} ${chromosomeLength}
paste ${output}_preproc_intermediate.txt $mappability_file  > temp.txt
mv temp.txt ${output}_preproc_intermediate.txt

# check for gc correction, if yes correct 
# check whether to correct with Yoon method or Loess Method
if [[ $MEDIANGCFLAG -eq 1 ]]; then
	runMedianGCcorrection ${output}_preproc_intermediate.txt $gcFile ;
elif [[ $LOESSGCFLAG -eq 1 ]]; then
	runLoessGCcorrection ${output}_preproc_intermediate.txt $gcFile
fi

# check for mappability correction, if yes correct it 
if [[ $MEDIANMAPFLAG -eq 1 ]]; then
	runMedianMapCorrection ${output}_preproc_intermediate.txt
fi


awk -v mapThres="$mapThres" '{if($3!=0 && $4>=mapThres) print $3;}' ${output}_preproc_intermediate.txt > ${output}_pCNVD.input;
awk -v mapThres="$mapThres" '{if($3!=0 && $4>=mapThres) print $1,$2;}' {output}_preproc_intermediate.txt > ${output}_pCNVD.bincor;

rm ${output}_preproc_intermediate.txt


